# Generated by Django 5.0.3 on 2024-04-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usertype", models.CharField(default="buyer", max_length=20)),
                ("fname", models.CharField(max_length=30)),
                ("lname", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.BigIntegerField(unique=True)),
                ("password", models.CharField(max_length=15)),
                ("pimage", models.ImageField(default="", upload_to="pimage/")),
            ],
        ),
    ]
