# Generated by Django 5.0.3 on 2024-04-18 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_user_pimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="usertype",
        ),
    ]
