# Generated by Django 5.0.3 on 2024-04-19 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_remove_user_usertype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="lname",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fname",
        ),
    ]
