# Generated by Django 5.0.3 on 2024-04-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_rename_lname_user_name_remove_user_fname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.BigIntegerField(max_length=10),
        ),
    ]
