# Generated by Django 5.0.3 on 2024-04-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_user_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.BigIntegerField(),
        ),
    ]
