# Generated by Django 5.0.3 on 2024-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(default="", upload_to="pictures/"),
        ),
    ]
