# Generated by Django 5.0.3 on 2024-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.BigIntegerField(unique=True),
        ),
    ]
