# Generated by Django 5.0.3 on 2024-05-08 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_user_email_alter_user_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="buyer", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pcategory",
                    models.CharField(
                        choices=[("Juice", "Juice"), ("Fruits", "Fruits")],
                        max_length=20,
                    ),
                ),
                ("pprice", models.PositiveIntegerField()),
                ("pname", models.CharField(max_length=50)),
                ("pdesc", models.TextField()),
                ("pimage", models.ImageField(default="", upload_to="pimage/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
