# Generated by Django 5.0.3 on 2024-05-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_user_email_alter_user_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pimage",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
        migrations.AddField(
            model_name="product",
            name="spimage",
            field=models.ImageField(default="", upload_to="spimage/"),
        ),
        migrations.AddField(
            model_name="user",
            name="pimage",
            field=models.ImageField(default="", upload_to="pimage/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=10),
        ),
    ]
