# Generated by Django 5.0.3 on 2024-05-22 12:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="spimage",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pimage",
        ),
        migrations.AddField(
            model_name="product",
            name="pimage",
            field=models.ImageField(default="", upload_to="pimage/"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ImageField(default="", upload_to="pictures/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("payment", models.BooleanField(default=False)),
                ("cqty", models.PositiveIntegerField(default=1)),
                ("tprice", models.PositiveIntegerField()),
                ("cprice", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
