from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('index', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('contact/', views.contact, name='contact'),
    path('news/', views.news, name='news'),
    path('shop/', views.shop, name='shop'),
    path('single_news/', views.single_news, name='single_news'),
    path('single_product/', views.single_product, name='single_product'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cpass/', views.cpass, name='cpass'),
    path('fpass/', views.fpass, name='fpass'),
    path('otp/', views.otp, name='otp'),
    path('newpass/', views.newpass, name='newpass'),
    path('uprofile/', views.uprofile, name='uprofile'),
    path('sindex/', views.sindex, name='sindex'),
    path('scontact/', views.scontact, name='scontact'),
    path('sadd/', views.sadd, name='sadd'),
    path('sview/', views.sview, name='sview'), 
    path('pdetails/<int:pk>/', views.pdetails, name='pdetails'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('bppdetails/<int:pk>/', views.bppdetails, name='bppdetails'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('addwish/<int:pk>', views.addwish, name='addwish'),
    path('dwish/<int:pk>', views.dwish, name='dwish'),
    path('cart/', views.cart, name='cart'),
    path('addcart/<int:pk>', views.addcart, name='addcart'),
    path('dcart/<int:pk>', views.dcart, name='dcart'),
    path('changeqty/<int:pk>', views.changeqty, name='changeqty'),
    path('sucess/',views.sucess,name='sucess'),
    path('myorder/',views.myorder,name='myorder'),
]